# Generated by Django 2.1.7 on 2019-05-04 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20190504_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Waiting', 'รอการอนุมัติ'), ('Acknowledge', 'รับทราบการสั่งจอง'), ('Send', 'กำลังทำการส่งของ'), ('Delivered', 'ส่งของเรียบร้อยแล้ว')], max_length=30),
        ),
    ]
